apiVersion: v1
kind: Service
metadata:
  name: my-server
  labels:
    app: my-server
    tier: api

spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
    nodePort:
  type: LoadBalancer
  selector:
    app: my-server
    tier: api
