apiVersion: v1
kind: ReplicationController
metadata:
  name: my-server2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: my-server
        tier: api
        deployment: v2
    spec:
      containers:
      - name: my-server
        image: gcr.io/cotb-140101/demoserver/2.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 8080
